spring:
  application:
    name: eurekaserver
#  security:
#    basic:
#      enabled: true
#    user:
#      name: mssistema-eureka-user
#      password: mua-msresrt-uaskeeise

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
